theme: jekyll-theme-cayman
title:        Guideline for Frequent Itemsets and Association Rules Mining on Spark
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
